HNCJ.DY.Web/Controllers/UserLoginController.cs
using HNCJ.DY.Common;
using HNCJ.DY.IBLL;
using HNCJ.DY.Model;
using HNCJ.DY.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HNCJ.DY.Web.Controllers
{
    [MyActionFilter(IsCheckUserLogin=false)]
    public class UserLoginController : Controller
    {
        //
        // GET: /UserLogin/
        public IUserInfoService UserInfoService { get; set; }

        
        #region 验证码
        /// <summary>
        /// 生成验证码
        /// </summary>
        /// <returns>返回一张图片</returns>
        public ActionResult ShowVcode()
        {
            Common.ValidateCode validateCode = new Common.ValidateCode();
            string code = validateCode.CreateValidateCode(4);
            Session["code"] = code;
            byte[] image = validateCode.CreateValidateGraphic(code);
            return File(image, @"image/jpeg");
        } 
        #endregion

        #region 管理员登陆
        public ActionResult adminLogin()
        {
            return View();
        }
        
        /// <summary>
        /// 管理员登录请求
        /// </summary>
        /// <returns></returns>
        public ActionResult adminProcessLogin()
        {
            string code = Session["code"] as string;
            Session["code"] = null;
            string vcode = Request["vCode"] as string;
            if (string.IsNullOrEmpty(code))
            {
                return Json(new { status = 0, msg = "验证码为空！" });
            }
            if (string.IsNullOrEmpty(vcode))
            {
                return Json(new { status = 0, msg = "验证码为空！" });
            }
            if (!code.Equals(vcode))
            {
                return Json(new { status = 0, msg = "验证码错误！" });
            }
            string name = Request["LoginCode"];
            string pwd = Request["LoginPwd"];
            if (string.IsNullOrEmpty(name) && string.IsNullOrEmpty(pwd)) {
                return Json(new { status = 0, msg = "用户名或密码不能为空？？" });
            }
            if (!UserInfoService.Exits(name)) {
                return Json(new { status = 0, msg = "用户不存在？？" });
            }
            UserInfo userInfo = UserInfoService.GetModel(name, pwd, true);
            if (userInfo == null)
            {
                return Json(new { status = 0, msg = "密码错误！" });
            }
            //立即分配一个标志Guid，把标志作为memcache存储数据的key，把用户对象放到memcache.把Guid写到客户端cookie里面去。
            string userLoginId = Guid.NewGuid().ToString();
            Common.Cache.CacheHelper.AddCache(userLoginId, userInfo, DateTime.Now.AddMinutes(20));
            //往客户端写入cookie
            Utils.WriteCookie("userLoginId", userLoginId, 14400);

            //Response.Cookies["userLoginId"].Value = userLoginId;
            return Json(new { status = 1, msg = "登陆成功！" });

        } 
        #endregion

        #region 用户登陆
        public ActionResult Login()
        {
            return View();
        }
        /// <summary>
        /// 用户登录请求
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ProcessLogin()
        {
            string code = Session["code"] as string;
            Session["code"] = null;
            string vcode = Request["ucode"] as string;
            if (string.IsNullOrEmpty(code))
            {
                return Json(new { status = 0, msg = "验证码为空！" });
            }
            if (string.IsNullOrEmpty(vcode))
            {
                return Json(new { status = 0, msg = "验证码为空！" });
            }
            if (!code.Equals(vcode))
            {
                return Json(new { status = 0, msg = "验证码错误！" });
            }
            string name = Request["tel"];
            string pwd = Request["pwd"];
            if (string.IsNullOrEmpty(name) && string.IsNullOrEmpty(pwd))
            {
                return Json(new { status = 0, msg = "用户名或密码不能为空？？" });
            }
            if (!UserInfoService.Exits(name))
            {
                return Json(new { status = 0, msg = "用户不存在？？" });
            }
            UserInfo userInfo = UserInfoService.GetModel(name, pwd, true);
            if (userInfo == null)
            {
                return Json(new { status = 0, msg = "密码错误？？" });
            }
            //立即分配一个标志Guid，把标志作为memcache存储数据的key，把用户对象放到memcache.把Guid写到客户端cookie里面去。
            string userLoginId = Guid.NewGuid().ToString();
            Common.Cache.CacheHelper.AddCache(userLoginId, userInfo, DateTime.Now.AddMinutes(20));
            //往客户端写入cookie
            Utils.WriteCookie("userLoginId", userLoginId, 14400);

            //Response.Cookies["userLoginId"].Value = userLoginId;
            return Json(new { status = 1, msg = "登陆成功！" });

        } 
        #endregion

        #region 用户注册
        public ActionResult registsubmit()
        {
            string code = Session["code"] as string;
            Session["code"] = null;
            string vcode = Request["vucode"] as string;
            if (string.IsNullOrEmpty(code))
            {
                return Json(new { status = 0, msg = "验证码为空！" });
            }
            if (string.IsNullOrEmpty(vcode))
            {
                return Json(new { status = 0, msg = "验证码为空！" });
            }
            if (!code.Equals(vcode))
            {
                return Json(new { status = 0, msg = "验证码错误！" });
            }
            string name = Request["tel"];
            string pwd = Request["pwd"];
            string pwd1 = Request["pwd1"];
            if (UserInfoService.Exits(name))
            {
                return Json(new { status = 0, msg = "用户名已存在！！" }); 
            }
            if (!pwd.Equals(pwd1)) {
                return Json(new { status = 0, msg = "两次密码不一致！！" }); 
            }
            UserInfo userInfo =new UserInfo();
            userInfo.UserName = name;
            userInfo.RegTime = DateTime.Now;
            userInfo.ModfiedTime = DateTime.Now;
            userInfo.DelFlag = true;
            userInfo.Status = 1;
            userInfo.UserKey = Utils.GetCheckCode(6); //获得6位的salt加密字符串
            userInfo.Userpwd = DESEncrypt.Encrypt(pwd, userInfo.UserKey);
            UserInfoService.Add(userInfo);
            UserInfoService.AddPaityMember(userInfo.ID);            
            
            //立即分配一个标志Guid，把标志作为memcache存储数据的key，把用户对象放到memcache.把Guid写到客户端cookie里面去。
            string userLoginId = Guid.NewGuid().ToString();
            Common.Cache.CacheHelper.AddCache(userLoginId, userInfo, DateTime.Now.AddMinutes(20));
            //往客户端写入cookie
            Utils.WriteCookie("userLoginId", userLoginId, 14400);

            //Response.Cookies["userLoginId"].Value = userLoginId;
            return Json(new { status = 1, msg = "登陆成功！" });
            
        }
        #endregion
    }
}

HNCJ.DY.Web/Views/UserLogin/Login.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录注册</title>
    <link href='http://fonts.googleapis.com/css?family=Days+One' rel='stylesheet' type='text/css'>
    <link href="~/Content/jquery-easyui-1.5/themes/icon.css" rel="stylesheet" />
    <link href="~/Content/jquery-easyui-1.5/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/dy/bootstrap-3.3.5-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/dy/css/login.css" rel="stylesheet" />
    <script src="~/Content/jquery-easyui-1.5/jquery.min.js"></script>
    <script src="~/Content/jquery-easyui-1.5/jquery.easyui.min.js"></script>
    <script src="~/Content/dy/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function denglu() {
            
            if ($("#tel").val() == "" || $("#pwd").val() == "") {
                $.messager.alert('提示', '请填写用户名和登录密码！', 'info');
                changeCheckCode();
                return false;
            }
            $.ajax({
                type: "post",             
                url: $("#dengluform").attr("url"),
                data: { tel: $("#tel").val(), pwd: $("#pwd").val(), ucode: $("#ucode").val() },
                dataType: "json",
                success: function (data) {
                    if (data.status == 1) {
                        window.location.href = "/users/index";
                    } else {
                        
                        $.messager.alert('提示', data.msg, 'info');
                        
                    }
                }
            
            });
            
            return false;
        }
        function registbtn() {
            if ($("#tels").val() == "") {
                $.messager.alert('提示', '请填写用户名！', 'info');
                changeCheckCode();
                return false;
            }
            if ($("#pwds").val() == "" || $("#pwd1").val() == "") {
                $.messager.alert('提示', '请填写密码！！！', 'info');
                changeCheckCode();
                return false;
            }
            if ($("#pwds").val() != $("#pwd1").val()) {
                $.messager.alert('提示', '两次密码不一致！！', 'info');
                changeCheckCode();
                return false;
            }
            $.ajax({
                type: "post",
                url: $("#registform").attr("url"),
                data: { tel: $("#tels").val(), pwd: $("#pwds").val(), pwd1: $("#pwd1").val(), vucode: $("#vucode").val() },
                dataType: "json",
                success: function (data) {
                    if (data.status == 1) {
                        window.location.href = "/users/index";
                    } else {
                        
                        $.messager.alert('提示', data.msg, 'info');
                        
                    }
                }

            });
            
            return false;
        }
        
    </script>
</head>
<body>

         <div class="index-main-body">
             <div class="index-header">
                 <h1 class="logo hide-text">党员"一点通"</h1>
                 <p class="subtitle">为党的建设提供更好的平台</p>
             </div>
             <div class="index-content" id="zhuce">
                 <div class="index-tab-nav">
                     <div class="nav-slider">
                         <a class="zhu" href="#">注册</a>
                         <div class="nav-slider-zhu"></div>
                     </div>
                     <div class="nav-slider2 nav-slider">
                          <a class="deng" href="#">登录</a>
                          <div class="nav-slider-deng"></div>
                     </div>
                 </div>
                 <div class="nav-deng">
                     <form id="dengluform" class="message2" novalidate="novalidate" url="/UserLogin/ProcessLogin" >
                         <input type="tel" value=""id="tel" name="tel" placeholder="手机号(仅支持中国大陆)" required/><br>
                         <input  type="password" value=""id="pwd" name="pwd"  placeholder="密码" required/><br>
                         <div class="yanzheng2">
                             <input type="password" value=""id="ucode" name="ucode" onkeydown="if(event.keyCode==13){denglu();}"  placeholder="验证码" required/><br>
                             <div class="img2">
                                 <a href="javascript:void(0)" onclick="changeCheckCode();return false;">
                                 <img class="imgs" src="/UserLogin/ShowVcode/?id=1" style="width: 120px;height: 45px" alt="" /></a>
                             </div>
                         </div>

                     </form>
                     <button class="but-deng" onclick="denglu();" >登录</button>
                 </div>
             </div>
             <div class="index-content2">
                 
                 <div class="nav-zhu">
                     <form id="registform" class="message" novalidate="novalidate" url="/userlogin/registsubmit">
                        
                        <input type="tel" value="" id="tels" name="tel" placeholder="手机号(仅支持中国大陆)" required/><br>
                        <input  type="password" value="" id="pwds" name="pwd"  placeholder="密码" required/><br>
                        <input type="password" value="" id="pwd1" name="pwd1"   placeholder="确认密码" required/><br>
                         <div class="yanzheng">
                             <input type="password" value="" id="vucode" name="vucode"   placeholder="验证码" required/><br>
                             <div class="img">
                                <a href="javascript:void(0)" onclick="changeCheckCode();return false;">
                                 <img class="imgs" src="/UserLogin/ShowVcode/?id=1" style="width: 120px;height: 45px" alt="" /></a>
                             </div>
                         </div>
                         
                     </form>
                     <button class="but-zhu" onclick="registbtn();">注册</button>
                     <div class="nav-agree">
                         <p>点击"注册"按钮,即代表你同意 <a href="#">《党建协议》</a></p>
                     </div>
                 </div>
             </div>


         </div>

     <footer >
         <nav class="nav navbar-default navbar-fixed-bottom" role="navigation">
             <ol class="breadcrumb text-center">
                 <li><a href="#">版权声明</a></li>
                 <li><a href="#">网站公告</a></li>
                 <li><a href="#">广告招商</a></li>
                 <li><a href="#">联系我们</a></li>
                 <li><a href="#">本站帮助</a></li>
             </ol>
         </nav>
     </footer>
</body>
</html>
<script src="~/Content/dy/js/login.js"></script>

HNCJ.DY.Web/Views/UserLogin/adminLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>   
    <title>后台系统登录</title>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script type="text/javascript">
        if (window.parent.window != window) {
            window.top.location.href = "/UserLogin/adminLogin";
        }
        function changeCheckCode() {
            $("#img").attr("src", $("#img").attr("src") + 1);
        }
        function afterLogin(data) {
            
            if (data.status==1) {
                window.location.href = $("#url").val();
            } else if (data.status==0) {
                changeCheckCode();
                alert(data.msg);
            } else {
                changeCheckCode();
                alert(data.msg);
            }
        }
    </script>

    <style type="text/css">
        *
        {
            padding: 0;
            margin: 0;
        }
        body
        {
            text-align: center;
            background: #4974A4;
        }
        #login
        {
            width: 740px;
            margin: 0 auto;
            font-size: 12px;
        }
        #loginlogo
        {
            width: 700px;
            height: 100px;
            overflow: hidden;
            background: url('/Content/Images/login/logo.png') no-repeat;
            margin-top: 50px;
        }
        #loginpanel
        {
            width: 729px;
            position: relative;
            height: 300px;
        }
        .panel-h
        {
            width: 729px;
            height: 20px;
            background: url('/Content/Images/login/panel-h.gif') no-repeat;
            position: absolute;
            top: 0px;
            left: 0px;
            z-index: 3;
        }
        .panel-f
        {
            width: 729px;
            height: 13px;
            background: url('/Content/Images/login/panel-f.gif') no-repeat;
            position: absolute;
            bottom: 0px;
            left: 0px;
            z-index: 3;
        }
        .panel-c
        {
            z-index: 2;
            background: url('/Content/Images/login/panel-c.gif') repeat-y;
            width: 729px;
            height: 300px;
        }
        .panel-c-l
        {
            position: absolute;
            left: 60px;
            top: 40px;
        }
        .panel-c-r
        {
            position: absolute;
            right: 20px;
            top: 50px;
            width: 222px;
            line-height: 200%;
            text-align: left;
        }
        .panel-c-l h3
        {
            color: #556A85;
            margin-bottom: 10px;
        }
        .panel-c-l td
        {
            padding: 7px;
        }
        .login-text
        {
            height: 24px;
            left: 24px;
            border: 1px solid #e9e9e9;
            background: #f9f9f9;
        }
        .login-text-focus
        {
            border: 1px solid #E6BF73;
        }
        .login-btn
        {
            width: 114px;
            height: 29px;
            color: #E9FFFF;
            line-height: 29px;
            background: url('/Content/Images/login/login-btn.gif') no-repeat;
            border: none;
            overflow: hidden;
            cursor: pointer;
        }
        #txtUserNum, #code, #txtPassword
        {
            width: 191px;
        }
        #logincopyright
        {
            text-align: center;
            color: White;
            margin-top: 50px;
        }
        a
        {
            color: Black;
        }
        a:hover
        {
            color: Red;
            text-decoration: underline;
        }
    </style>
    

</head>
<body style="padding: 10px">

    <div id="login">
        <div id="loginlogo">
        </div>
        <div id="loginpanel">
            <div class="panel-h">
            </div>
            <div class="panel-c">
                <div class="panel-c-l">
                @using (Ajax.BeginForm("adminProcessLogin", "UserLogin", new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterLogin" }, new { id = "loginForm" }))
                {
                    <table cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <td align="left" colspan="2">
                                    <h3>
                                        欢迎来到后台登陆界面</h3>
                                </td>
                            </tr>
                            <tr>
                                <td align="right">
                                    账号：
                                </td>
                                <td align="left">
                                    <input type="text" name="LoginCode" id="LoginCode" class="login-text"value="admin"  />
                                   
                                </td>
                            </tr>
                            <tr>
                                <td align="right">
                                    密码：
                                </td>
                                <td align="left">
                                    <input type="password" name="LoginPwd" id="LoginPwd" value="123456" class="login-text"  />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    验证码：
                                </td>
                                <td align="left">
                                    <input type="text" class="login-text" id="code" name="vCode" style="width:110px;" value="" />
                                    
                                    <div style="float:right;margin-left: 1px;">
                                        <a href="javascript:void(0)" onclick="changeCheckCode();return false;"><img id="img" src="/UserLogin/ShowVcode/?id=1" style=" height: 24px;" /></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                               
                                <td colspan="2">
                                    <select name="url" id="url" class="login-text" >
                                        <option value="/home/index">主题风格-风尚版</option>
                                        <option value="/home/layout">主题风格-经典版</option>
                                        
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" colspan="2">
                                    <input type="submit" id="btnLogin" value="登录" class="login-btn" />
                                    <span id="errorMsg"></span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }

                </div>
                <div class="panel-c-r">
                    <p>
                        请从左侧输入登录账号和密码登录</p>
                    <p>
                        如果遇到系统问题，请联系网络管理员。</p>
                    <p>
                        如果没有账号，请联系网站管理员。
                    </p>
                    <p>
                        ......</p>
                </div>
            </div>
            <div class="panel-f">
            </div>
        </div>
        <div id="logincopyright">
            Copyright ? 2012 HNCJ.OA
        </div>
    </div>
</body>
</html>