HNCJ.DY.Web/Controllers/HomeController.cs
using HNCJ.DY.IBLL;
using HNCJ.DY.Model;
using HNCJ.DY.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HNCJ.DY.Web.Controllers
{
    public class HomeController : BaseController
    {
        public IUserInfoService UserInfoService { get; set; }
        public IRoleInfoService RoleInfoService { get; set; }
        public IActionInfoService ActionInfoService { get; set; }
        
        //
        // GET: /Home/
        
        public ActionResult Layout() {
            ViewData.Model = this.LoginUser;
            ViewBag.AllMenu = LoadUserMenu();
            return View();
        }
        public ActionResult Index()
        {
            ViewData.Model = this.LoginUser;
            ViewBag.AllMenu = LoadUserMenu();
            return View();
        }
        #region 加载菜单图标
        public List<ActionInfo> LoadUserMenu()
        {
            int userId = this.LoginUser.ID;
            var user = UserInfoService.GetEntity(u => u.ID == userId && u.DelFlag == true).FirstOrDefault();
            var allRole = user.RoleInfo;
            var allRoleActionIds = (from r in allRole
                                    from a in r.ActionInfo
                                    select a.ID).ToList();
            var allDenyActionIds = (from r in user.UserActionInfo
                                    where r.HasPermissin == 0
                                    select r.ActionInfoID).ToList();
            var allActionIds = (from a in allRoleActionIds
                                where !allDenyActionIds.Contains(a)
                                select a).ToList();
            var allUserActionIds = (from t in user.UserActionInfo
                                    where t.HasPermissin == 1 && t.DelFlag == true
                                    select t.ActionInfoID).ToList();
            //把当前用户所有权限拿到
            allActionIds.AddRange(allUserActionIds.AsEnumerable());
            allActionIds = allActionIds.Distinct().ToList();//去重复值
            var actionList = ActionInfoService.GetEntity(a => allActionIds.Contains(a.ID) && a.IsMenu == true && a.DelFlag == true).ToList();
            if (LoginUser.UserName == "admin")
            {
                actionList = ActionInfoService.GetEntity(a => a.IsMenu == true && a.DelFlag == true).ToList();
            }

            return actionList;
        } 
        #endregion

        public ActionResult center() {
            return View();
        }
        public ActionResult Print() {
            ViewData.Model = LoginUser;
            return View();
        }
        public ActionResult details() {
            ViewData.Model = LoginUser;
            return View();
        }
        [MyActionFilter(IsCheckUserLogin = false)]
        public ActionResult IndexPage() {
            return Redirect("/Content/home/code/first_page.html");
        }
        
    }
}

HNCJ.DY.Web/Controllers/UserDoActionController.cs
using HNCJ.DY.Common;
using HNCJ.DY.IBLL;
using HNCJ.DY.Model;
using HNCJ.DY.Web.Models;
using Microsoft.Reporting.WinForms;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HNCJ.DY.Web.Controllers
{
    [MyActionFilter(IsCheckUserLogin = false)]
    public class UserDoActionController : Controller
    {
        //
        // GET: /UserDoAction/
        public IUserInfoService UserInfoService { get; set; }
        public IActionInfoService ActionInfoService { get; set; }

        #region 上传图片
        public ActionResult UploadImage()
        {
            HttpPostedFileBase postFile = Request.Files["Filedata"];//接收文件
            //文件保存目录路径
            string path = Request["name"];

            String savePath = "/Upload/Images/";
            string fileName = Path.GetFileName(postFile.FileName);//文件名称
            string fileExt = Path.GetExtension(fileName);//文件的扩展名
            String ymd = DateTime.Now.ToString("yyyyMMdd", DateTimeFormatInfo.InvariantInfo);
            savePath += ymd + "/";            
            String dirPath = Request.MapPath(savePath);
            if (!Directory.Exists(dirPath))
            {
                Directory.CreateDirectory(dirPath);
            }
            
            string newfileName = Guid.NewGuid().ToString();//新的文件名
            string fileDir = savePath + newfileName + fileExt;//完整的路径
            postFile.SaveAs(Request.MapPath(fileDir));//保存文件
            if (!string.IsNullOrEmpty(path)) {
                FileInfo file = new FileInfo(Server.MapPath(path));//指定文件路径
                if (file.Exists)//判断文件是否存在
                {
                    file.Attributes = FileAttributes.Normal;//将文件属性设置为普通,比方说只读文件设置为普通
                    file.Delete();//删除文件
                }
            }
            return Json(new { path = fileDir }, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region 上传文件
        public ActionResult UploadFile()
        {
            HttpPostedFileBase postFile = Request.Files["Filedata"];//接收文件
            string name = Request["name"];
            //文件保存目录路径
            String savePath = "/Upload/Files/";

            string fileName = Path.GetFileName(postFile.FileName);//文件名称
            if (string.IsNullOrEmpty(name))
            {
                string[] dd = fileName.Split('.');
                name = dd[0];
            }
            string fileExt = Path.GetExtension(fileName);//文件的扩展名
            String ymd = DateTime.Now.ToString("yyyyMMdd", DateTimeFormatInfo.InvariantInfo);
            savePath += ymd + "/";
            string dirpath = Request.MapPath(savePath);
            if (!Directory.Exists(dirpath))
            {
                Directory.CreateDirectory(dirpath);
            }

            string newfileName = Guid.NewGuid().ToString();//新的文件名
            string fileDir = savePath + newfileName + fileExt;//完整的路径
            postFile.SaveAs(Request.MapPath(fileDir));//保存文件

            return Json(new { path = fileDir, name = name, format = fileExt }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UploadFile1()
        {
            HttpPostedFileBase postFile = Request.Files["Filedata"];//接收文件
            string path = Request["path"];
            //文件保存目录路径
            String savePath = "/Upload/Files/";

            string fileName = Path.GetFileName(postFile.FileName);//文件名称
            if (!string.IsNullOrEmpty(path))
            {
                FileInfo file = new FileInfo(Server.MapPath(path));//指定文件路径
                if (file.Exists)//判断文件是否存在
                {
                    file.Attributes = FileAttributes.Normal;//将文件属性设置为普通,比方说只读文件设置为普通
                    file.Delete();//删除文件
                }
            }
            string fileExt = Path.GetExtension(fileName);//文件的扩展名
            String ymd = DateTime.Now.ToString("yyyyMMdd", DateTimeFormatInfo.InvariantInfo);
            savePath += ymd + "/";
            string dirpath = Request.MapPath(savePath);

            if (!Directory.Exists(dirpath))
            {
                Directory.CreateDirectory(dirpath);
            }
            string newfileName = Guid.NewGuid().ToString();//新的文件名
            string fileDir = savePath + newfileName + fileExt;//完整的路径
            postFile.SaveAs(Request.MapPath(fileDir));//保存文件

            return Json(new { path = fileDir, name = newfileName, format = fileExt }, JsonRequestBehavior.AllowGet);
        } 
        #endregion

        #region 下载
        public FileStreamResult DownLoad(string path)
        {
            if (string.IsNullOrEmpty(path)) {
                return null;
            }
            string filepath = Server.MapPath(path);
            FileInfo file = new FileInfo(filepath);
            if (!file.Exists) {
                return null;
            }
            string[] str = path.Split('/');
            return File(new FileStream(filepath, FileMode.Open), "application/octet-stream", str[str.Length - 1]);
        }
        #endregion

        #region 判断是否登陆
        [HttpPost]
        public ActionResult Check_login()
        {
            HttpCookie cookie = Request.Cookies["userLoginId"];
            if (cookie == null)
            {
                return Json(new { status=0});
            }

            string userGuid = cookie.Value;
            if (Common.Cache.CacheHelper.GetCache(userGuid) == null)
            {
                return Json(new { status = 0 });
            }
            return Json(new { status=1});
        }
        #endregion

        #region 注销操作
        public ActionResult Exits()
        {
            HttpCookie cookie = Request.Cookies["userLoginId"];
            string userGuid = cookie.Value;
            Common.Cache.CacheHelper.SetCache(userGuid, "", DateTime.Now.AddMonths(-1));
            if (cookie != null)
            {
                cookie.Value = null;
                cookie.Expires = DateTime.Now.AddDays(-1);
            }
            Response.Cookies.Add(cookie);
            return Redirect("/Content/bigdatalogin/bigdatalogin.html");

        }
        public ActionResult AdminExits()
        {
            HttpCookie cookie = Request.Cookies["userLoginId"];
            string userGuid = cookie.Value;
            Common.Cache.CacheHelper.SetCache(userGuid, "", DateTime.Now.AddMonths(-1));
            if (cookie != null)
            {
                cookie.Value = null;
                cookie.Expires = DateTime.Now.AddDays(-1);
            }
            Response.Cookies.Add(cookie);
            return RedirectToAction("AdminLogin", "UserLogin");

        }
        #endregion

        #region 注册操作
        public ActionResult register()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Register(UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                userInfo.RegTime = DateTime.Now;
 
                userInfo.DelFlag = true;
                userInfo.UserKey = Utils.GetCheckCode(6); //获得6位的salt加密字符串
                userInfo.Userpwd = DESEncrypt.Encrypt(userInfo.Userpwd, userInfo.UserKey);
                UserInfo user = UserInfoService.Add(userInfo);
                if (user == null)
                {
                    return Content("no");
                }
                string userLoginId = Guid.NewGuid().ToString();
                Common.Cache.CacheHelper.AddCache(userLoginId, user, DateTime.Now.AddMinutes(20));
                //往客户端写入cookie
                Response.Cookies["userLoginId"].Value = userLoginId;
                return Content("ok");
            }
            return Content("no");
        }
        #endregion

        #region 导出表格
//        .doc     application/msword
//.docx   application/vnd.openxmlformats-officedocument.wordprocessingml.document
//.rtf       application/rtf
//.xls     application/vnd.ms-excel	application/x-excel
//.xlsx    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
//.ppt     application/vnd.ms-powerpoint
//.pptx    application/vnd.openxmlformats-officedocument.presentationml.presentation
//.pps     application/vnd.ms-powerpoint
//.ppsx   application/vnd.openxmlformats-officedocument.presentationml.slideshow
//.pdf     application/pdf
//.swf    application/x-shockwave-flash
//.dll      application/x-msdownload
//.exe    application/octet-stream
//.msi    application/octet-stream
//.chm    application/octet-stream
//.cab    application/octet-stream
//.ocx    application/octet-stream
//.rar     application/octet-stream
//.tar     application/x-tar
//.tgz    application/x-compressed
//.zip    application/x-zip-compressed
//.z       application/x-compress
//.wav   audio/wav
//.wma   audio/x-ms-wma
//.wmv   video/x-ms-wmv
//.mp3 .mp2 .mpe .mpeg .mpg     audio/mpeg
//.rm     application/vnd.rn-realmedia
//.mid .midi .rmi     audio/mid
//.bmp     image/bmp
//.gif     image/gif
//.png    image/png
//.tif .tiff    image/tiff
//.jpe .jpeg .jpg     image/jpeg
//.txt      text/plain
//.xml     text/xml
//.html     text/html
//.css      text/css
//.js        text/javascript
//.mht .mhtml   message/rfc822
        public FileContentResult ExportExcel()
        {
            var data = ActionInfoService.GetEntity(u => u.DelFlag == true).ToList();
            var list = data.Select(u => new { u.ID,u.ActionName, u.Url, u.HttpMethd, IsMenu = (bool)u.IsMenu ? "是" : "否" }).ToList();
            LocalReport lr = new LocalReport();
            //设置报表格式
            string deviceInfo = "<DeviceInfo>" + "<SimplePageHeaders>True</SimplePageHeaders>" + "</DeviceInfo>";
            //设置报表路径
            lr.ReportPath = Server.MapPath("~/Report/Report1.rdlc");
            //设置数据源
            ReportDataSource rd = new ReportDataSource();
            rd.Name = "DataSet1";
            rd.Value = list;
            lr.DataSources.Add(rd);

HNCJ.DY.Web/Views/Home/Index.cshtml
@model HNCJ.DY.Model.UserInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DY办公系统</title>
    
    <link href="~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" />
    <script src="~/Content/lib/jquery/jquery-1.9.0.min.js"></script>
    <script src="~/Content/lib/ligerUI/js/core/base.js"></script>
    <script src="~/Content/lib/ligerUI/js/ligerui.all.js"></script>
    <style type="text/css">
       

        a {font-size:16px;font-family:'Adobe Devanagari';font-synthesis:weight;}   
        a:link {color: blue; text-decoration:none;} 
        a:active{color: red;text-decoration:none; }
        a:visited {color:purple;text-decoration:none;}   
        a:hover {color: red; text-decoration:none;} 

        .l-case-title
        {
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        body, html
        {
            width: 100%;
            height: 100%;
        }
        *
        {
            margin: 0;
            padding: 0;
        }
        #winlinks
        {
            position: absolute;
            left: 20px;
            top: 20px;
            width: 100%;
        }
        #winlinks ul
        {
            position: relative;
        }
        #winlinks li
        {
            width: 70px;
            cursor: pointer;
            height: 80px;
            position: absolute;
            z-index: 101;
            list-style: none;
            text-align: center;
        }
        #winlinks li img
        {
            width: 36px;
            height: 36px;
        }
        #winlinks li span
        {
            background: none repeat scroll 0 0 rgba(0, 0, 0, 0.3);
            border-radius: 10px 10px 10px 10px;
            display: block;
            font-size: 12px;
            margin-top: 1px;
            color: White;
            line-height: 18px;
            text-align: center;
        }
        #winlinks li.l-over div.bg
        {
            display: block;
        }
        #winlinks li div.bg
        {
            display: none;
            position: absolute;
            top: -2px;
            left: -2px;
            z-index: 0;
            width: 75px;
            height: 64px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            background: #000;
            opacity: 0.1;
            filter: alpha(opacity=10);
        }
        .l-taskbar-task-icon
        {
            top: 3px; left: 6px; background-image:none;
        } 
        .l-taskbar-task-content{ margin-left:30px;}
        .l-taskbar-task-icon img
        {
            width: 22px;
            height: 22px;
        }
    </style>
    <script type="text/javascript">
        $(function () {
            $("#layout1").ligerLayout();
        });
    </script>
</head>
<body >
    <div  class="l-page-top" style=" background: url(../Content/Images/task/logo3.jpg) repeat-x;height:67px; ">
        <img src="~/Content/lib/images/logo.png" style="height:67px;" />
        <div style="margin:25px 10px 0 0;float:right;font-size:16px;font-family:'Adobe Devanagari';color: blue;">
            你好,&nbsp;<a href="#" >@Model.UserName</a>&nbsp;|
            <a href="/userdoaction/adminExits" class="">注销</a>
        </div>
    </div>
    <div id="layout1" style="margin:0;overflow: hidden;" >
            <div position="center" style="overflow: hidden; background: url(../Content/Images/task/gravity.jpg) no-repeat  center center;" >
            <div id="winlinks" >
                <ul>
                </ul>
            </div>
            </div>
            
        </div> 

    
</body>
    <script type="text/javascript">
        var LINKWIDTH = 90, LINKHEIGHT = 90, TASKBARHEIGHT = 43;
        var winlinksul = $("#winlinks ul");
        function f_open(url, title, icon) {
            var win = $.ligerDialog.open(
            {
                height: 500, url: url, width: 750, showMax: true, showToggle: true, showMin: true,overflow:'hidden', isResize: true, modal: false, title: title, slide: false, buttons: [
                  {
                      text: '确定', onclick: function (item, Dialog, index) {
                          win.hide();
                      }
                  }
                ]
            });
            var task = jQuery.ligerui.win.tasks[win.id];
            if (task) {
                $(".l-taskbar-task-icon:first", task).html('<img src="' + icon + '" />');
            }
            return win;
        }
    @{
        List<HNCJ.DY.Model.ActionInfo> menus = ViewBag.AllMenu as List<HNCJ.DY.Model.ActionInfo>;
        System.Text.StringBuilder sb = new System.Text.StringBuilder();
        foreach(var item in menus){
            sb.Append("{");
            sb.Append("icon: '" + item.MenuIcon + "', title: '" + item.ActionName + "', url: '" + item.Url + "'"); 
            sb.Append("},");
        }
        string str=sb.ToString().TrimEnd(',');
     }
        var links = [
            @Html.Raw(str)
        //        { icon: 'Content/windows/icon/big.png', title: '填写周报', url: '/userinfo/index' },
        //        { icon: 'Content/Images/Alien%20Folder.png', title: 'treegrid', url: '../grid/treegrid/treegrid.htm' },
        //        { icon: 'Content/images/3DSMAX.png', title: '多表头', url: '../grid/mulheader/grid2.htm' },
        //        { icon: 'Content/images/Program Files Folder.png', title: '固定列', url: '../grid/frozen/frozengrid.htm' },
        //        { icon: 'Content/images/Program Files Folder.png', title: '可拖动', url: '../base/drag.htm' },
        //        { icon: 'Content/images/Alien Folder.png', title: '树', url: '../tree/draggable.htm' },
        //        { icon: 'Content/images/Xp-G5 006.png', title: '下拉框', url: '../comboBox/comboBoxGrid.htm' },
        //        { icon: 'Content/images/Xp-G5 006.png', title: '下拉框', url: '../comboBox/comboBoxGrid.htm' },
        //        { icon: 'Content/images/Alien Folder.png', title: 'layout', url: '../layout/layoutFullHeight.htm' },
        //         { icon: 'Content/images/Alien Folder.png', title: 'menu', url: '../menu/menubar.htm' },
        //         { icon: 'Content/images/Xp-G5 006.png', title: 'tab', url: '../tab/tabHtml.htm' },
        //         { icon: 'Content/images/3DSMAX.png', title: '分组', url: '../grid/groupable/checkbox.htm' }
        ];

        function onResize() {
            var linksHeight = $(window).height() - TASKBARHEIGHT;
            var winlinks = $("#winlinks");
            winlinks.height(linksHeight);
            var colMaxNumber = parseInt(linksHeight / LINKHEIGHT);//一列最多显示几个快捷方式
            for (var i = 0, l = links.length; i < l; i++) {
                var link = links[i];
                var jlink = $("li[linkindex=" + i + "]", winlinks);
                var top = (i % colMaxNumber) * LINKHEIGHT, left = parseInt(i / colMaxNumber) * LINKWIDTH;
                if (isNaN(top) || isNaN(left)) continue;
                jlink.css({ top: top, left: left });
            }

        }
        function linksInit() {
            for (var i = 0, l = links.length; i < l; i++) {
                var link = links[i];
                var jlink;
                var jlink = $("<li></li>");
                jlink.attr("linkindex", i);
                jlink.append("<img src='" + link.icon + "' />");
                jlink.append("<span>" + link.title + "</span>");
                jlink.append("<div class='bg'></div>");
                jlink.hover(function () {
                    $(this).addClass("l-over");
                }, function () {
                    $(this).removeClass("l-over");
                }).click(function () {
                    var linkindex = $(this).attr("linkindex");
                    var link = links[linkindex];
                    f_open(link.url, link.title, link.icon);
                });
                jlink.appendTo(winlinksul);
            }

        }

        $(window).resize(onResize);
        $.ligerui.win.removeTaskbar = function () { }; //不允许移除
        $.ligerui.win.createTaskbar(); //页面加载时创建任务栏

        linksInit();
        onResize();



</script>

</html>

HNCJ.DY.Web/Views/Home/Layout.cshtml
@model HNCJ.DY.Model.UserInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>后台管理系统</title>
    <link href="~/Content/html.css" rel="stylesheet" />
    <link href="~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" />
    <script src="~/Content/lib/jquery/jquery-1.9.0.min.js"></script>
    <script src="~/Content/lib/ligerUI/js/core/base.js"></script>
    <script src="~/Content/lib/ligerUI/js/ligerui.min.js"></script>
    <script type="text/javascript">
        var tab = null;
        $(function () {

            $("#layout1").ligerLayout({ topHeight: 67, leftWidth: 200, allowTopResize: false, allowLeftResize: false, allowRightResize: false, allowBottomResize: false });
            $("#accordion1").ligerAccordion();
            var height = $(".l-layout-center").height();
            var width = $(".l-layout-center").width();

            var tab = $("#navtab1").ligerTab({ height: height, width: width });
            binClickEvent();

        });
      
        function binClickEvent() {
            $(".btnclick").click(function () {
                var title = $(this).text();
                var url = $(this).attr("url");
                var tabid = $(this).attr("id");
                f_addTab(tabid, title, url);
            });
        }
        function f_addTab(tabid, text, url) {
            var tab = liger.get("navtab1");
            
            tab.addTabItem({
                tabid: tabid,
                text: text,
                url: url
                
            });
        }

     </script> 
    <style type="text/css">
        body{ padding:5px; margin:0;}
        #layout1{  width:100%; margin:40px;  height:400px;
                   margin:0; padding:0;} 
        #accordion1 { height:270px;}
         h4{ margin:20px;}
         a{color:#475059;text-decoration:none;}
a:hover,a:active,a:focus{outline:none;text-decoration:none;color:#72afd2}
         ul,li,h1,h2,h3,h4,h5,h6,dl,dt,dd{padding:0;margin:0;}
ul{list-style:none}
        li {
            padding-left:30px;
            margin-top:5px;
        }
    </style>

 
</head>
<body>
    <div id="layout1">
             <div  position="left">
                 <div id="accordion1" style="height:100%"> 
         <div title="功能列表" data-icon="/Content/lib/ligerUI/skins/icons/calendar.gif">
             
              <ul>
                  @if (ViewBag.AllMenu != null) {
                      List<HNCJ.DY.Model.ActionInfo> list = ViewBag.AllMenu as List<HNCJ.DY.Model.ActionInfo>;
                      foreach (var item in list) { 
                      <li>
                         <a href="javascript:void(0);" class="btnclick" id="@item.ID" url="@item.Url" style="font-family:'Angsana New';font-size:15px;"  >@item.ActionName</a></li>
                      }
                  }
                    
                    
                </ul>
        </div>
         <div title="列表">
                <ul>
                    <li>列表一</li>
                    <li>列表二</li>
                    <li>列表三</li>
                    <li>列表四</li>
                    <li>列表五</li>
                </ul>
        </div> 
        <div title="其他" style="padding:10px"> 
        其他内容
        </div>
    </div>  


             </div>
            <div position="center" id="framecenter" >
                
                <div id="navtab1" style="width: 100%;height:100%; overflow:hidden; ">
                    <div tabid="home" title="我的主页" lselected="true"  style="height:100%;width:100%;overflow:hidden;" >
                        <iframe frameborder="0" id="showmessage" name="showmessage" src="/home/center"></iframe> 
                    </div>
                </div>
            </div>
            
            <div position="top" border="false" style="height: 65px; background: #B3DFDA; overflow: hidden;background-image: url('../../Content/Images/bg3.png'); ">
                <img src="~/Content/lib/images/logo.png" style="height:67px;" />
                <div style="margin:25px 10px 0 0;float:right;font-size:16px;font-family:'Adobe Devanagari';color: blue;">
            你好,&nbsp;<a href="#" class="btnclick" id="admin" url="/home/details" >@Model.UserName</a>&nbsp;|
            <a href="/userdoaction/adminExits" class="">注销</a>
        </div>
            </div>
            <div position="bottom" style="height:30px;background:#A9FACD;padding:10px; text-align:center">版权  &copy;  HNCJ.DY</div>
        </div> 
           
     

</body>
</html>

HNCJ.DY.Web/Views/Home/Print.cshtml
@model HNCJ.DY.Model.UserInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Print</title>
    <link href="~/Content/artdialog/ui-dialog.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Content/artdialog/dialog-plus-min.js"></script>

    <script type="text/javascript">
        //打印订单
        function OrderPrint() {
            var winDialog = top.dialog({
                title: '打印基本信息',
                url: '/home/details',
                width: 850
            }).showModal();
        }
        function prinf() {
            OrderPrint();
        }
    </script>
</head>
<body>
    
    <a href="#" onclick="prinf();">打印</a>
    @Html.ActionLink("导出表格", "ExportExcel", "UserDoAction");
</body>
</html>

HNCJ.DY.Web/Views/Home/center.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>center</title>
</head>
<body>
    <div>
        
        欢迎使用！
    </div>
</body>
</html>

HNCJ.DY.Web/Views/Home/details.cshtml
@model HNCJ.DY.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>details</title>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script type="text/javascript">
        var api = top.dialog.get(window); //获取父窗体对象
        //页面加载完成执行
        $(function () {
            //设置按钮及事件
            api.button([{
                value: '确认打印',
                callback: function () {
                    printWin();
                },
                autofocus: true
            }, {
                value: '取消',
                callback: function () { }
            }]);
        });
        //打印方法
        function printWin() {
            var oWin = window.open("", "_blank");
            oWin.document.write(document.getElementById("content").innerHTML);
            oWin.focus();
            oWin.document.close();
            oWin.print();
            oWin.close();
            return false;
        }
</script>
    <style type="text/css">
       
        
        
    </style>
</head>
<body>
    <div id="content" style="flex-align:center;">
    <table align="center"  width="600" border="1" cellspacing="0" cellpadding="5" style="font-size:12px; font-family:'微软雅黑'; background:#fff;">
		<tr>
			<td >姓名</td>
			<td >XXX</td>
			<td >性别</td>
			<td >如实填写</td>
			<td rowspan="4" >正面免冠图片</td>
		</tr>
		<tr>
			<td>名族</td>
			<td>X</td>
			<td>出生年月</td>
			<td>XXXX年XX月</td>
			
		</tr>
		<tr>
			<td>籍贯</td>
			<td>X省X市X县</td>
			<td>出生地</td>
			<td>X省X市X县</td>
			
		</tr>
		<tr>
			<td>学历</td>
			<td>相当大学本科</td>
			<td>学位或昵称</td>
			<td>无</td>
			
		</tr>
		<tr>
			<td colspan="2">单位</td>
			<td colspan="3">X学院X班X职务</td>
		</tr>
		<tr>
			<td colspan="2">现居住地</td>
			<td colspan="3">市（县）乡（镇）村（街道办事处）</td>
		</tr>
		<tr>
			<td colspan="2">居民身份证号码</td>
			<td colspan="3">如实填写</td>
		</tr>
		<tr>
			<td colspan="2">有何专长</td>
			<td colspan="3">如实填写</td>
		</tr>
		<tr>
			<td colspan="5">入党志愿</td>
		</tr>
	</table>
    </div>
</body>
</html>